### PR TITLE
add `org.cryptomator:jfuse` aggregator jar

### PR DESCRIPTION
**Pull request by overheadhunter**
With this PR, instead of this

```xml
<dependency>
	<groupId>org.cryptomator</groupId>
	<artifactId>jfuse-api</artifactId>
	<version>x.y.z</version>
</dependency>
<dependency>
	<groupId>org.cryptomator</groupId>
	<artifactId>jfuse-linux-amd64</artifactId>
	<version>x.y.z</version>
</dependency>
<dependency>
	<groupId>org.cryptomator</groupId>
	<artifactId>jfuse-linux-aarch64</artifactId>
	<version>x.y.z</version>
</dependency>
<dependency>
	<groupId>org.cryptomator</groupId>
	<artifactId>jfuse-mac</artifactId>
	<version>x.y.z</version>
</dependency>
<dependency>
	<groupId>org.cryptomator</groupId>
	<artifactId>jfuse-win</artifactId>
	<version>x.y.z</version>
</dependency>
```

dependent projects just need this:

```xml
<dependency>
	<groupId>org.cryptomator</groupId>
	<artifactId>jfuse</artifactId>
	<version>x.y.z</version>
</dependency>
```

This does not change the fact, that we still need `--enable-native-access=org.cryptomator.jfuse.linux.amd64` etc at runtime.

### CODE REVIEW

**Review by infeo — CHANGES_REQUESTED** [review]
Mhm, of course due to the enforcer rules running the root pom with `-Pjextract` will always fail. This is not optimal, maybe add four different jextract profiles `jextract-linux-aarch64` to `jextract-win` ?

**Comment by infeo** [comment]
Oih and when implementing it, update the jextract section in the readme as well

**Comment by overheadhunter** [comment]
> Mhm, of course due to the enforcer rules running the root pom with `-Pjextract` will always fail.

I decided this is actually a good thing. We don't want to accidentally harm jextracted code on platform X, when we run jextract on platform Y. Therefore I added an enforcer rule to fail hard in the parent pom on such an attempt.

This way we don't need multiple jextract-xyz profiles (trying to keep the project clean). Also updated the readme files and relaxed enforcer rules for system-specific modules, since there is no point in enforcing an OS as long as the headers are available.

**Review by infeo — CHANGES_REQUESTED** [review]
Executing maven for a subproject with `-Pjextract` fails with the enforcer message from the parent procject. Are the enforcer rules by any chances inherited by the module?

**Review by infeo — APPROVED** [review]

**Pull request merged**
